DailyCostWebApplication/ViewModels/CreateUserViewModel.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel;

namespace DailyCostWebApplication.ViewModels
{
    public class CreateUserViewModel
    {
        [Required]
        [EmailAddress]
        public string Email { get; set; }
        [Required]
        [DataType(DataType.Password)]
        public string Password { get; set; }
        [Required]
        [DataType(DataType.Password)]
        [DisplayName("Confirm Password")]
        [Compare("Password", ErrorMessage = "The Confirm Password Does Not Match With Password")]
        public string ConfirmPassword { get; set; }
    }
}

DailyCostWebApplication/ViewModels/SignInViewModel.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel;

namespace DailyCostWebApplication.ViewModels
{
    public class SignInViewModel
    {
        [Required]
        [EmailAddress]
        public string Email { get; set; }
        [Required]
        [DataType(DataType.Password)]
        public string Password { get; set; }
        [DisplayName("Remember Me")]
        public bool RememberMe { get; set; }
    }
}

DailyCostWebApplication/Controllers/UserManagmentController.cs
using DailyCostWebApplication.ViewModels;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System.Threading.Tasks;

namespace DailyCostWebApplication.Controllers
{
    public class UserManagmentController : Controller
    {
        private readonly UserManager<IdentityUser> userManger;
        private readonly SignInManager<IdentityUser> signInManager;

        public UserManagmentController(UserManager<IdentityUser> _userManger, SignInManager<IdentityUser> _signInManager)
        {
            userManger = _userManger;
            signInManager = _signInManager;
        }
        [HttpGet]
        public IActionResult CreateUser()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> CreateUser(CreateUserViewModel createUserViewModel)
        {
            if (ModelState.IsValid)
            {
                IdentityUser user = 
                    new IdentityUser { UserName = createUserViewModel.Email, Email = createUserViewModel.Email };
                var result = await userManger.CreateAsync(user, createUserViewModel.Password);
                if (result.Succeeded)
                {
                    ViewBag.RegisteredResult = "Yes";
                    ModelState.Clear();
                }
                else
                {
                    ViewBag.RegisteredResult = "No";
                    foreach(var error in result.Errors)
                    {
                        ModelState.AddModelError("Validation", error.Description);
                    }
                }
            }
            return View();
        }

        [HttpGet]
        public IActionResult SignIn()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> SignIn(SignInViewModel signIn)
        {
            if (ModelState.IsValid)
            {
                var result = await signInManager.PasswordSignInAsync(signIn.Email, signIn.Password, signIn.RememberMe, true);
                if(result.Succeeded)
                {
                    return RedirectToAction("Index", "Home");
                }
                ModelState.AddModelError("", "UserName or Password is incorrect");
            }
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> SignOut()
        {
            await signInManager.SignOutAsync();
            return RedirectToAction("Index", "Home");
        }
    }
}

DailyCostWebApplication/Views/UserManagment/CreateUser.cshtml
@model CreateUserViewModel
@{
    ViewBag.Title = "Create New User";
}
<form asp-controller="UserManagment" asp-action="CreateUser" method="post" class="mt-5 offset-3 col-6 border border-primary pt-2 pb-2 px-2 py-2">
    <div>
        <label asp-for="Email" class="form-label"></label>
        <input asp-for="Email" class="form-control" />
        <span asp-validation-for="Email" class="text-danger"></span>
    </div>
    <div>
        <label asp-for="Password" class="form-label"></label>
        <input asp-for="Password" class="form-control" />
        <span asp-validation-for="Password" class="text-danger"></span>
    </div>
    <div>
        <label asp-for="ConfirmPassword" class="form-label"></label>
        <input asp-for="ConfirmPassword" class="form-control" />
        <span asp-validation-for="ConfirmPassword" class="text-danger"></span>
    </div>
    <div><button type="submit" class="btn btn-primary mt-2">Save</button></div>
    <div asp-validation-summary="All" class="text-danger"></div>
</form>
@if (ViewBag.RegisteredResult == "Yes")
{
    <div class="alert alert-success mt-2 offset-3 col-6" role="alert">
        Your account was successfully registered
    </div>
}
@if (ViewBag.RegisteredResult == "No")
{
    <div class="alert alert-danger mt-2 offset-3 col-6" role="alert">
        Internal Error: The user has not been created!
    </div>
}

DailyCostWebApplication/Views/UserManagment/SignIn.cshtml
@model SignInViewModel
@{
    ViewBag.Title = "Login";
}
<form asp-controller="UserManagment" asp-action="SignIn" method="post" class="mt-5 offset-3 col-6 border border-primary pt-2 pb-2 px-2 py-2">
    <div>
        <label asp-for="Email" class="form-label"></label>
        <input asp-for="Email" class="form-control" />
        <span asp-validation-for="Email" class="text-danger"></span>
    </div>
    <div>
        <label asp-for="Password" class="form-label"></label>
        <input asp-for="Password" class="form-control" />
        <span asp-validation-for="Password" class="text-danger"></span>
    </div>
    <div class="form-check">
        <input asp-for="RememberMe" class="form-check-input" type="checkbox" id="rememberMe">
        <label asp-for="RememberMe" class="form-check-label" for="rememberMe"></label>
    </div>
    <div><button type="submit" class="btn btn-primary mt-2">Sign In</button></div>
    <div asp-validation-summary="All" class="text-danger"></div>
</form>