DailyCostWebApplication/Models/Cost.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace DailyCostWebApplication.Models
{
    public class Cost
    {
        [Key]
        public int ID { get; set; }
        [Column(TypeName = "decimal(18, 2)")]
        [Required]
        public decimal Amount { get; set; }
        [Required]
        [DataType(DataType.Date)]
        public DateTime RegisteredDate { get; set; }
        [MaxLength(150)]
        public string Comment { get; set; }
        [Required]
        [RegularExpression("^\\d+$", ErrorMessage = "Please select a category")]
        public int CategoryID { get; set; }
        [ForeignKey(nameof(CategoryID))]
        public virtual Category Category { get; set; }
        [Required(ErrorMessage = "This option is mandetory, please select a payment method")]
        public PaymentMethods? PaymentMethod { set; get; }
        public string InvoiceImagePath { get; set; }
    }
}

DailyCostWebApplication/Controllers/CostController.cs
using DailyCostWebApplication.Models;
using DailyCostWebApplication.ViewModels;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using X.PagedList;

namespace DailyCostWebApplication.Controllers
{
    //[Route("[Controller]/[action]")]
    public class CostController : Controller
    {
        private readonly ICostRepository costRepository;
        private readonly ICategoryRepository categoryRepository;
        private readonly IWebHostEnvironment webHostEnvironment;

        public CostController(ICostRepository _costRepository, ICategoryRepository _categoryRepository, 
            IWebHostEnvironment _webHostEnvironment)
        {
            costRepository = _costRepository;
            categoryRepository = _categoryRepository;
            webHostEnvironment = _webHostEnvironment;
        }

        [HttpGet]
        public IActionResult Create()
        {
            LoadDropdownList();
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(CreateCostViewModel model)
        {
            if (ModelState.IsValid)
            {
                Cost cost = new()
                {
                    Amount = model.Amount,
                    Comment = model.Comment,
                    RegisteredDate = model.RegisteredDate,
                    CategoryID = model.CategoryID,
                    PaymentMethod = model.PaymentMethod
                };
                if(model.UploadFile != null)
                {
                    cost.InvoiceImagePath = UploadFile(model.UploadFile);
                }
                costRepository.Create(cost);
                return RedirectToAction("Index");
            }
            LoadDropdownList();
            return View(model);
        }
        [HttpGet]
        public IActionResult Index(string searchby, string searchfor, int? page, string sortby)
        {
            var costs = costRepository.GetCostList(searchby, searchfor,sortby).ToPagedList(page ?? 1, 5);
            return View(costs);
        }
        [HttpGet]
        public IActionResult Detail(int id)
        {
            var cost = costRepository.GetCostByID(id);
            return View(cost);
        }
        [HttpGet]
        public IActionResult Update(int id)
        {
            var cost = costRepository.GetCostByID(id);
            UpdateCostViewModel model = new()
            {
                ID = cost.ID,
                Amount = cost.Amount,
                RegisteredDate = cost.RegisteredDate,
                Comment = cost.Comment,
                CategoryID = cost.CategoryID,
                PaymentMethod = cost.PaymentMethod,
                ExsitingFile = cost.InvoiceImagePath
            };
            LoadDropdownList();
            return View(model);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Update(UpdateCostViewModel model)
        {
            if (ModelState.IsValid)
            {
                Cost UpdatedCost = costRepository.GetCostByID(model.ID);
                UpdatedCost.Amount = model.Amount;
                UpdatedCost.RegisteredDate = model.RegisteredDate;
                UpdatedCost.Comment = model.Comment;
                UpdatedCost.CategoryID = model.CategoryID;
                UpdatedCost.PaymentMethod = model.PaymentMethod;
                if(model.UploadFile != null)
                {
                    if(UpdatedCost.InvoiceImagePath != null)
                    {
                        string ExitingFile = Path.Combine(webHostEnvironment.WebRootPath, "images", UpdatedCost.InvoiceImagePath);
                        System.IO.File.Delete(ExitingFile);
                    }
                    UpdatedCost.InvoiceImagePath = UploadFile(model.UploadFile);
                }
                costRepository.Update(UpdatedCost);
                return RedirectToAction("Index");
            }
            LoadDropdownList();
            return View(model);
        }
        [ValidateAntiForgeryToken]
        [HttpPost]
        public IActionResult Delete(int id)
        {
            Cost cost = costRepository.GetCostByID(id);
            if (cost.InvoiceImagePath != null)
            {
                string ExitingFile = Path.Combine(webHostEnvironment.WebRootPath, "images", cost.InvoiceImagePath);
                System.IO.File.Delete(ExitingFile);
            }
            costRepository.Delete(id);
            return RedirectToAction("index");
        }
        private void LoadDropdownList()
        {
            var Categories = categoryRepository.GetAllCategories();
            List<SelectListItem> CatList = new();
            CatList.Add(new SelectListItem("Select a Category", "-1"));
            foreach (var category in Categories)
            {
                CatList.Add(new SelectListItem(category.CategoryName, category.ID.ToString()));
            }
            List<SelectListItem> PaymentList = new();
            PaymentList.Add(new SelectListItem("Select a Payment Method", ""));
            var PaymentMethod = Enum.GetValues(typeof(PaymentMethods)).Cast<PaymentMethods>().ToList();
            for (var i = 0; i < PaymentMethod.Count(); i++)
            {
                PaymentList.Add(new SelectListItem(PaymentMethod[i].ToString(), i.ToString()));
            }
            ViewBag.Categories = CatList;
            ViewBag.PaymentMethods = PaymentList;
        }
        private string UploadFile(IFormFile formFile)
        {
            string UniqueFileName = Guid.NewGuid().ToString() + "-" + formFile.FileName;
            string TargetPath = Path.Combine(webHostEnvironment.WebRootPath, "images", UniqueFileName);
            using (var stream = new FileStream(TargetPath, FileMode.Create))
            {
                formFile.CopyTo(stream);
            }
            return UniqueFileName;
        }


    }
 
}

DailyCostWebApplication/Views/Cost/Create.cshtml
@model CreateCostViewModel

@{
    ViewBag.Title = "Create Cost";
}
<form enctype="multipart/form-data" asp-controller="Cost" asp-action="Create" method="post" class="mt-5 offset-3 col-6 border border-primary pt-2 pb-2 px-2 py-2">
    <div>
        <label asp-for="Amount" class="form-label"></label>
        <input asp-for="Amount" class="form-control" />
        <span asp-validation-for="Amount" class="text-danger"></span>
    </div>
    <div>
        <label asp-for="RegisteredDate" class="form-label"></label>
        <input asp-for="RegisteredDate" class="form-control" />
        <span asp-validation-for="RegisteredDate" class="text-danger"></span>
    </div>
    <div>
        <label asp-for="Comment" class="form-label"></label>
        <input asp-for="Comment" class="form-control" />
        <span asp-validation-for="Comment" class="text-danger"></span>
    </div>
    <div>
        <label asp-for="CategoryID" class="form-label"></label>
        <select asp-for=CategoryID asp-items="@ViewBag.Categories" class="form-select"></select>
        <span asp-validation-for="CategoryID" class="text-danger"></span>
    </div>
    <div>
        <label asp-for="PaymentMethod" class="form-label"></label>
        <select asp-for="PaymentMethod" class="form-select" asp-items="@ViewBag.PaymentMethods"></select>
        <span asp-validation-for="PaymentMethod" class="text-danger"></span>
    </div>
    <div>
        <label asp-for="UploadFile" class="form-label"></label>
        <input asp-for="UploadFile" class="form-control" />
    </div>
    <div><button type="submit" class="btn btn-primary mt-2">Create</button></div>
</form>

DailyCostWebApplication/Views/Cost/Detail.cshtml
@model Cost
@{
    ViewBag.Title = "Cost Detail";
    var imagepath = "~/images/" + (Model.InvoiceImagePath ?? "no-image.png");
}
<div class="row">
    <div class="col-lg-4 offset-lg-4 col-md-6 offset-md-3 col-12">
        <div class="card">
            <img  src="@imagepath" class="card-img-top" asp-append-version="true"/>
            <div class="card-header">
                Detail Cost ID @Model.ID
            </div>
            <div class="card-body">
                <p class="card-text">Amount: @Model.Amount</p>
                <p class="card-text">Category: @Model.CategoryID</p>
                <p class="card-text">Comment: @Model.Comment</p>
                <p class="card-text">Payment Method: @Model.PaymentMethod</p>
                <a class="btn btn-primary" asp-controller="cost" asp-action="index">Cost List</a>
            </div>
        </div>
    </div>
</div>

DailyCostWebApplication/Views/Cost/Index.cshtml
@model IEnumerable<CostList>
@using X.PagedList;
@using X.PagedList.Mvc.Core;
@{
    ViewBag.Title = "Cost List";
}
<div class="row">
    <div class=col-3>
        <a asp-controller="cost" asp-action="create" class="btn btn-primary mx-2 my-2">Create New Cost</a>
    </div>
    <div class="col-6 offset-3">
        <form asp-controller="Cost" asp-action="Index" method="get" class="my-2 mx-2">
            <div class="input-group">
                <select class="form-select" id="inputSearch" name="searchby">
                    <option selected value="">Search by...</option>
                    <option value="comment">Comment</option>
                    <option value="category">Category</option>
                </select>
                <input name="searchfor" class="form-control" id="inputSearch" aria-describedby="inputSearchComment" aria-label="Search">
                <button class="btn btn-outline-secondary" type="submit" id="inputSearch">Search</button>
                <a class="btn btn-outline-primary" type="button" asp-controller="cost" asp-action="index">Clear Search</a>
            </div>
        </form>
    </div>
</div>
<table class="table table-dark">
    <thead>
        <tr>
            <th>ID</th>
            @{
                var sortBy = Context.Request.Query["sortby"] == "amount" ? "amountdesc" : "amount";
            }
            <th><a asp-action="index" asp-route-sortby="@sortBy" 
                asp-route-page="@Context.Request.Query["page"]"
                asp-route-searchby="@Context.Request.Query["searchby"]"
                asp-route-searchfor="@Context.Request.Query["searchfor"]">Amount</a></th>
            <th>Category</th>
            <th>Comment</th>
            @{
                sortBy = Context.Request.Query["sortby"] == "paymentmethod" ? "paymentmethoddesc" : "paymentmethod";
            }
            <th><a asp-action="index" asp-route-sortby="@sortBy"
                asp-route-page="@Context.Request.Query["page"]"
                asp-route-searchby="@Context.Request.Query["searchby"]"
                asp-route-searchfor="@Context.Request.Query["searchfor"]">Payment Method</a></th>
            <th colspan="3" class="text-center">Actions</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var cost in Model)
        {
            <tr>
                <td>@cost.ID</td>
                <td>@cost.Amount</td>
                <td>@cost.CategoryName</td>
                <td>@cost.Comment</td>
                <td>@cost.PaymentMethod</td>
                <form asp-controller="cost" asp-action="delete" asp-route-id="@cost.ID" method="post">
                <td><a class="btn btn-primary d-block" asp-controller="cost" asp-action="detail" asp-route-id="@cost.ID">View</a></td>
                <td><a class="btn btn-info btn-block d-block" asp-controller="cost" asp-action="update" asp-route-id="@cost.ID">Edit</a></td>
                <td><button class="btn btn-danger btn-block d-block" type="submit">Delete</button></td>
                </form>
            </tr>
        }
    </tbody>
</table>
@Html.PagedListPager((IPagedList) Model, page => Url.Action("Index", new {page = page,
searchfor = @Context.Request.Query["searchfor"],
searchby = @Context.Request.Query["searchby"],
sortby = @Context.Request.Query["sortby"]}),
new X.PagedList.Web.Common.PagedListRenderOptions {
    LiElementClasses = new string[] {"page-item"},
    PageClasses = new string[] { "page-link" }
})

DailyCostWebApplication/Views/Cost/Update.cshtml
@model UpdateCostViewModel
@{
    ViewBag.Title = "Create Cost";
    var imagepath = "~/images/" + (Model.ExsitingFile ?? "no-image.png");
}
<form asp-controller="Cost" enctype="multipart/form-data" asp-action="Update" method="post" class="mt-5 offset-3 col-6 border border-primary pt-2 pb-2 px-2 py-2">
    <input hidden asp-for="ID" />
    <div>
        <label asp-for="Amount" class="form-label"></label>
        <input asp-for="Amount" class="form-control" />
        <span asp-validation-for="Amount" class="text-danger"></span>
    </div>
    <div>
        <label asp-for="RegisteredDate" class="form-label"></label>
        <input asp-for="RegisteredDate" class="form-control" />
        <span asp-validation-for="RegisteredDate" class="text-danger"></span>
    </div>
    <div>
        <label asp-for="Comment" class="form-label"></label>
        <input asp-for="Comment" class="form-control" />
        <span asp-validation-for="Comment" class="text-danger"></span>
    </div>
    <div>
        <label asp-for="CategoryID" class="form-label"></label>
        <select asp-for=CategoryID asp-items="@ViewBag.Categories" class="form-select"></select>
        <span asp-validation-for="CategoryID" class="text-danger"></span>
    </div>
    <div>
        <label asp-for="PaymentMethod" class="form-label"></label>
        <select asp-for="PaymentMethod" class="form-select" asp-items="@ViewBag.PaymentMethods"></select>
        <span asp-validation-for="PaymentMethod" class="text-danger"></span>
    </div>
    <div>
        <label asp-for="UploadFile" class="form-label"></label>
        <input asp-for="UploadFile" class="form-control" />
    </div>
    <img src="@imagepath" asp-append-version="true" class="img-thumbnail"/>
    <div class="row mt-2">
        <div class="col-3 d-grid">
            <button type="submit" class="btn btn-primary">Edit</button>
        </div>
        <div class="col-3 d-grid">
            <a asp-action="index" class="btn btn-info">Cost List</a>
        </div>
    </div>
</form>